### ISSUE TITLE
屏幕旋转奔溃

### ISSUE THREAD

**Issue by qiushui95** [li-xiaojun/XPopup#10]
还没有显示dialog   旋转屏幕也会奔溃

**Comment by li-xiaojun** [comment]
@qiushui95 可以说下您的机型和系统，崩溃的话截个崩溃日志的图；您直接这样说，我很难定位问题所在。

**Comment by qiushui95** [comment]
应该和机型无关
2018-12-24 17:00:19.845 28719-28719/com.lxj.xpopupdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lxj.xpopupdemo, PID: 28719
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
        at com.lxj.xpopupdemo.fragment.QuickStartDemo.init(QuickStartDemo.java:28)
        at com.lxj.xpopupdemo.MainActivity.callFragmentInit(MainActivity.java:74)
        at com.lxj.xpopupdemo.MainActivity.access$000(MainActivity.java:21)
        at com.lxj.xpopupdemo.MainActivity$2.run(MainActivity.java:64)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6942)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by qiushui95** [comment]
将您的BaseFragment内的init放到onViewCreated内执行就可以了。
旋转屏幕过后fragment.getView()获取到的是null

**Comment by li-xiaojun** [comment]
@qiushui95 恩，多谢您提供的Issue。最新的Demo已修复这个Bug，可以下载看看。

**Comment by qiushui95** [comment]
你这个修复太牛逼了。。。。。。我尽无言以对

**Comment by li-xiaojun** [comment]
@qiushui95 就问你6不6
