### ISSUE TITLE
dismiss时，activity也onDestory

### ISSUE THREAD

**Issue by AlbertZyc** [li-xiaojun/XPopup#1004]
**XPopup版本**
如2.1.0

**手机系统和型号**
任意

**描述你的问题**
/**
abstract class CenterDialog<B : ViewDataBinding>(
    context: Context,
    @LayoutRes val layoutId: Int = -1
) :
    CenterPopupView(context) {
    protected var mBinding: B? = null
        private set

    override fun onCreate() {
        super.onCreate()
        mBinding = DataBindingUtil.bind(popupImplView)
        mBinding?.lifecycleOwner = this
        onInitContent()
        onInitViewAction()
    }
    open fun onInitViewAction(){}

    override fun getImplLayoutId(): Int {
        return layoutId
    }

    override fun onDestroy() {
        mBinding?.unbind()
        super.onDestroy()
    }

    abstract fun onInitContent()
}
**/
错误如下
2022-07-18 17:27:54.162 8674-8674/com.nf.bitcoinexchange E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nf.bitcoinexchange, PID: 8674
    java.lang.RuntimeException: Unable to destroy activity {com.nf.bitcoinexchange/com.nf.login_module.LoginActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5111)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:232)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:190)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:224)
        at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1498)
        at android.app.Activity.performDestroy(Activity.java:8241)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.IllegalStateException: no event up from DESTROYED
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:263)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at com.lxj.xpopup.core.BasePopupView.destroy(BasePopupView.java:775)
        at com.lxj.xpopup.core.BasePopupView.onDetachedFromWindow(BasePopupView.java:815)
        at com.lxj.xpopup.core.CenterPopupView.onDetachedFromWindow(CenterPopupView.java:78)
        at com.lxj.xpopup.core.BasePopupView.onDestroy(BasePopupView.java:769)
        at com.nf.framework.popudialog.interlayer.CenterDialog.onDestroy(CenterDialog.kt:39)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:222)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:190) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354) 
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68) 
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:224) 
        at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1498) 
        at android.app.Activity.performDestroy(Activity.java:8241) 
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344) 
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096) 
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2022-07-18 17:27:54.173 8674-8674/com.nf.bitcoinexchange I/Process: Sending signal. PID: 8674 SIG: 9

**Comment by li-xiaojun** [comment]
@AlbertZyc 更新最新版本试试

**Comment by AlbertZyc** [comment]
> @AlbertZyc 更新最新版本试试

新版本已经完成，可以说说为啥吗，我在提交记录里没找到相关的修改
