### ISSUE TITLE
.NullPointerException: Attempt to invoke virtual method 'int com.lxj.xpopup.core.BasePopupView.getActivityContentLeft()' on a null object reference

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1032]
**XPopup版本**
如2.9.0

**描述你的问题**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.lxj.xpopup.core.BasePopupView.getActivityContentLeft()' on a null object reference
       at com.lxj.xpopup.core.FullScreenDialog$1.run(FullScreenDialog.java:96)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by li-xiaojun** [comment]
更新到2.9.1即可
