### ISSUE TITLE
AttachPopupView crash

### ISSUE THREAD

**Issue by Duzilin1994** [li-xiaojun/XPopup#1048]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.Window.getDecorView()' on a null object reference
       at com.lxj.xpopup.util.XPopupUtils.isNavBarVisible(XPopupUtils.java:323)
       at com.lxj.xpopup.core.AttachPopupView.doAttach(AttachPopupView.java:114)
       at com.lxj.xpopup.core.AttachPopupView$1.run(AttachPopupView.java:65)
       at com.lxj.xpopup.util.XPopupUtils.lambda$null$0(XPopupUtils.java:182)
       at com.lxj.xpopup.util.XPopupUtils$$ExternalSyntheticLambda1.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

int realNavHeight = (XPopupUtils.isNavBarVisible(getHostWindow()) ? XPopupUtils.getNavBarHeight() : 0 );
如果getHostWindow() == null       realNavHeight直接赋值0比崩溃好吧

**Comment by Duzilin1994** [comment]
老哥看下怎么处理更好吧

**Comment by li-xiaojun** [comment]
不写版本号？

**Comment by Duzilin1994** [comment]
> 

所有版本

**Comment by Duzilin1994** [comment]
线上 xpop v2.7.8 出现的问题

**Comment by li-xiaojun** [comment]
更新到最新版本
