### ISSUE TITLE
NullPointerException: Attempt to read from field 'int com.lxj.xpopup.core.PopupInfo.maxHeight' 

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1053]
**XPopup版本**
如2.9.12-apl

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.lxj.xpopup.core.PopupInfo.maxHeight' on a null object reference
       at com.lxj.xpopup.core.BasePopupView.getMaxHeight(BasePopupView.java:626)
       at com.lxj.xpopup.core.BubbleAttachPopupView.doMeasure(BubbleAttachPopupView.java:71)
       at com.lxj.xpopup.core.BasePopupView$3.run(BasePopupView.java:230)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by li-xiaojun** [comment]
@billdizl 更新到2.9.13即可
