### ISSUE TITLE
CenterPopupView.java line 32 com.lxj.xpopup.core.CenterPopupView.addInnerContent

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1059]
**XPopup版本**
2.9.15

**手机系统和型号**
设备
品牌：LGE
型号：Nexus 5X
屏幕方向： 纵向
可用 RAM： 1.31 GB
可用磁盘空间： 376.87 MB
操作系统
版本：Android 8.1.0
屏幕方向： 纵向
是否已取得 root 权限：否
崩溃
日期：2022年11月26日 07:11:47

**描述你的问题**
CenterPopupView.java line 32
com.lxj.xpopup.core.CenterPopupView.addInnerContent

Caused by java.lang.UnsupportedOperationException: Can't convert value at index 14 to dimension: type=0x1
       at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:730)
       at android.content.res.XResources$XTypedArray.getDimensionPixelSize(XResources.java:1342)
       at android.view.View.<init>(View.java:4771)
       at android.view.ViewGroup.<init>(ViewGroup.java:597)
       at android.widget.RelativeLayout.<init>(RelativeLayout.java:248)
       at android.widget.RelativeLayout.<init>(RelativeLayout.java:244)
       at android.widget.RelativeLayout.<init>(RelativeLayout.java:240)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:647)
       at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at com.lxj.xpopup.core.CenterPopupView.addInnerContent(CenterPopupView.java:32)
       at com.lxj.xpopup.core.CenterPopupView.initPopupContent(CenterPopupView.java:46)
       at com.lxj.xpopup.core.BasePopupView.init(BasePopupView.java:262)
       at com.lxj.xpopup.core.BasePopupView.attachToHost(BasePopupView.java:173)
       at com.lxj.xpopup.core.BasePopupView.access$000(BasePopupView.java:57)
       at com.lxj.xpopup.core.BasePopupView$1.run(BasePopupView.java:111)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by li-xiaojun** [comment]
检查你getImplLayoutId方法返回的是什么
