### ISSUE TITLE
图片查看

### ISSUE THREAD

**Issue by chengzhuangjie** [li-xiaojun/XPopup#1075]
崩溃信息:
Canvas: trying to draw too large(199756800bytes) bitmap.

类名:RecordingCanvas.java

方法:throwIfCannotDraw

行数:266

类型:java.lang.RuntimeException

时间:2022-12-28_19:03

设备名称:M2012K11AC

设备厂商:Redmi

系统版本:Android 12-31

CPU-ABI:armeabi-v7a

versionCode:1

versionName:1.0

全部信息:
java.lang.RuntimeException: Canvas: trying to draw too large(199756800bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at android.widget.ImageView.onDraw(ImageView.java:1480)
	at android.view.View.draw(View.java:23015)
	at android.view.View.updateDisplayListIfDirty(View.java:21883)
	at android.view.View.draw(View.java:22741)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23019)
	at android.view.View.updateDisplayListIfDirty(View.java:21883)
	at android.view.View.draw(View.java:22741)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21874)
	at android.view.View.draw(View.java:22741)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23019)
	at android.view.View.updateDisplayListIfDirty(View.java:21883)
	at android.view.View.draw(View.java:22741)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21874)
	at android.view.View.draw(View.java:22741)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.updateDisplayListIfDirty(View.java:21874)
	at android.view.View.draw(View.java:22741)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4542)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4300)
	at android.view.View.draw(View.java:23019)
	at com.android.internal.policy.DecorView.draw(DecorView.java:880)
	at android.view.View.updateDisplayListIfDirty(View.java:21883)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4657)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4375)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3486)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2277)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9017)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8105)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by li-xiaojun** [comment]
使用SmartGlideImageLoader(true, 0)了吗？

**Comment by chengzhuangjie** [comment]
使用了new SmartGlideImageLoader()

**Comment by chengzhuangjie** [comment]
@li-xiaojun

**Comment by li-xiaojun** [comment]
> @li-xiaojun

用我发的那个构造，文档上都有说明的，
