### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: 如果弹窗对象是复用的，则不要设置isDestroyOnDismiss(true)

### ISSUE THREAD

**Issue by billdizl** [li-xiaojun/XPopup#1128]
**XPopup版本**
2.9.19

**手机系统和型号**
华为Mate20 Android 10

**描述你的问题**
Fatal Exception: java.lang.IllegalArgumentException: 如果弹窗对象是复用的，则不要设置isDestroyOnDismiss(true)
       at com.lxj.xpopup.core.BasePopupView.attachToHost(BasePopupView.java:129)
       at com.lxj.xpopup.core.BasePopupView.access$000(BasePopupView.java:59)
       at com.lxj.xpopup.core.BasePopupView$1.run(BasePopupView.java:119)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7880)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

如果设置了自动跟随生命周期,在注销的时候这个类destroy就会出现这种异常报错

**Comment by billdizl** [comment]
原因是因为我设置了basepop.customHostLifecycle(mLifecycle),然后在activity ondestroy时,调用了basepop.destory().则出现了该异常报错
