### ISSUE TITLE
混淆后 空指针 at com.lxj.xpopup.util.SmartGlideImageLoader.loadImage(Unknown Source:1)

### ISSUE THREAD

**Issue by easytobreakdown** [li-xiaojun/XPopup#1195]
**XPopup版本**
2.10.0
**描述你的问题**
混淆后 空指针:
 java.lang.NullPointerException
at com.lxj.xpopup.util.SmartGlideImageLoader.loadImage(Unknown Source:1)
at com.lxj.xpopup.core.ImageViewerPopupView$PhotoViewAdapter.instantiateItem(ImageViewerPopupView.java:492)
at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
不混淆则正常

**Comment by easytobreakdown** [comment]
AS清了缓存,项目重构几次 问题解决了.
