### ISSUE TITLE
【建议】ImageViewerPopupView 的 srcView 可否为null

### ISSUE THREAD

**Issue by ihewro** [li-xiaojun/XPopup#148]
现在的库，必须填写srcView，以便显示图片弹窗的渐进渐出的动画。

我的需求是点击 WebView  上面的图片，显示弹窗。WebView 加载的图片获取不到 imageView。

如果srcView 也可以设置为null 那就更灵活了。 这样只显示图片弹窗，去掉渐进渐出的动画就可以了

**Comment by li-xiaojun** [comment]
@ihewro 
兄弟，srcView用来确定动画从哪里开始，结束时回到哪里。如果不传给我srcView，那么弹窗效果就比较僵硬了，没有移动的动画了，就算我实现了，这个体验是很难受的。

**Comment by ihewro** [comment]
> @ihewro
> 兄弟，srcView用来确定动画从哪里开始，结束时回到哪里。如果不传给我srcView，那么弹窗效果就比较僵硬了，没有移动的动画了，就算我实现了，这个体验是很难受的。

我的意思就是不需要这个移动的动画，webView 点击图片直接打开一个弹窗（和打开一个一个activity动画一样），只需要弹窗内部的图片缩放功能

不知道我有没有表达清楚

**Comment by li-xiaojun** [comment]
好吧，你这个需求我加上吧，只能退而求其次了。

**Comment by ihewro** [comment]
> 好吧，你这个需求我加上吧，只能退而求其次了。

谢谢了！

**Comment by li-xiaojun** [comment]
@ihewro 
最新版本已经支持srcView传null，更新试试。

**Comment by ihewro** [comment]
```java
    @android.webkit.JavascriptInterface
    public void openImage(String img) {

        ALog.d("点击了图片" +img);
        // 单张图片场景
        new XPopup.Builder(context)
                .asImageViewer(null, img, new ImageLoader())
                .show();
    }

    class ImageLoader implements XPopupImageLoader {
        @Override
        public void loadImage(int position, @NonNull Object url, @NonNull ImageView imageView) {
            //必须指定Target.SIZE_ORIGINAL，否则无法拿到原图，就无法享用天衣无缝的动画
            Glide.with(imageView).load(url).apply(new RequestOptions().placeholder(R.mipmap.ic_launcher_round).override(Target.SIZE_ORIGINAL)).into(imageView);
        }

        @Override
        public File getImageFile(@NonNull Context context, @NonNull Object uri) {
            try {
                return Glide.with(context).downloadOnly().load(uri).submit().get();
            } catch (Exception e) {
                e.printStackTrace();
            }
            return null;
        }
    }

```

我是这么写的，不知道为什么没能显示出来？

` ALog.d("点击了图片" +img);`这一行已经正确打印出来了。不知道是否是什么地方没写对？

**Comment by li-xiaojun** [comment]
@ihewro 
图片url是否正确，查看下log的输出

**Comment by ihewro** [comment]
图片地址是正确的，下面是单击图片的的时候的log
```
2019-05-16 20:49:28.946 27160-27370/com.ihewro.focus D/MJavascriptInterface:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ JavaBridge, com.ihewro.focus.util.MJavascriptInterface.openImage(MJavascriptInterface.java:45)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ 点击了图片https://pic2.zhimg.com/50/v2-4e3ff30fda5ad3815736c209a185c7c8.jpg
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
2019-05-16 20:49:28.953 27160-27370/com.ihewro.focus I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-16 20:49:28.954 27160-27370/com.ihewro.focus I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-16 20:49:28.954 27160-27370/com.ihewro.focus D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-16 20:49:28.954 27160-27370/com.ihewro.focus D/FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
2019-05-16 20:49:28.954 27160-27370/com.ihewro.focus D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@3e9ea35,com.ihewro.focus.activity.PostDetailActivity@5a605ad
2019-05-16 20:49:28.954 27160-27370/com.ihewro.focus D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
2019-05-16 20:49:28.957 27160-27370/com.ihewro.focus I/FLTAG_FM: loadFeature class:com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-16 20:49:28.957 27160-27370/com.ihewro.focus I/FLTAG_SFM: getRequireClassLoader() succ ! className: com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-16 20:49:28.957 27160-27370/com.ihewro.focus D/FeatureFactory: loadFeature() : com.huawei.featurelayer.systemfeature.HwWidget.IHwSplineOverScrollerEx
2019-05-16 20:49:28.958 27160-27370/com.ihewro.focus D/FeatureFactory: loadFeature() new IHwSplineOverScrollerEx()
2019-05-16 20:49:28.961 27160-27370/com.ihewro.focus D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl paras: android.widget.OverScroller$SplineOverScroller@53b083b,com.ihewro.focus.activity.PostDetailActivity@5a605ad
2019-05-16 20:49:28.961 27160-27370/com.ihewro.focus D/HwSplineOverScrollerExImpl: initSplineOverScrollerImpl: mScrollerVelocity is 0, value is 0
2019-05-16 20:49:28.971 27160-27370/com.ihewro.focus W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.getLocationInWindow(int[])' on a null object reference
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at com.lxj.xpopup.core.ImageViewerPopupView.setSrcView(ImageViewerPopupView.java:382)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at com.lxj.xpopup.core.ImageViewerPopupView.setSingleSrcView(ImageViewerPopupView.java:374)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at com.lxj.xpopup.XPopup$Builder.asImageViewer(XPopup.java:489)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at com.ihewro.focus.util.MJavascriptInterface.openImage(MJavascriptInterface.java:48)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:386)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at android.os.Looper.loop(Looper.java:169)
2019-05-16 20:49:28.972 27160-27370/com.ihewro.focus W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
2019-05-16 20:49:28.976 27160-27160/com.ihewro.focus I/chromium: [INFO:CONSOLE(1)] "Uncaught Error: Java exception was raised during method invocation", source: data:text/html; charset=UTF-8,<html><header><link rel="stylesheet" type="text/css" href="https://focus.com/content.css"><style>.entry{font-size:16px;line-height:2;letter-spacing:0px;}</style>%0A</header><body class="entry "><a href="https://www.zhihu.com/people/bbacb42b80831c2d5f3b4047bad93dbf">ZOL%E4%B8%AD%E5%85%B3%E6%9D%91%E5%9C%A8%E7%BA%BF</a>%EF%BC%9A<div><a class="hash_tag" href="https://www.zhihu.com/pin/special/972884951192113152">%23%E6%AF%8F%E6%97%A5%E6%96%B0%E9%97%BB%23</a> %E3%80%90%E4%B8%89%E6%98%9FGalaxy Fold%E5%8D%B3%E5%B0%86%E5%9B%9E%E5%BD%92%EF%BC%9A%E9%A2%84%E8%AE%A16%E6%9C%88%E9%87%8D%E6%96%B0%E4%B8%8A%E5%B8%82%E3%80%91<br>%E5%8C%97%E4%BA%AC%E6%97%B6%E9%97%B45%E6%9C%8816%E6%97%A5%EF%BC%8C%E6%8D%AE%E5%A4%96%E5%AA%92%E6%8A%A5%E9%81%93%EF%BC%8C%E4%B8%89%E6%98%9F%E9%A6%96%E6%AC%BE%E6%8A%98%E5%8F%A0%E5%B1%8F%E6%89%8B%E6%9C%BAGalaxy Fold%E5%9C%A8%E7%BB%8F%E5%8E%86%E4%BA%86%E4%B8%80%E4%BA%9B%E6%B3%A2%E6%8A%98%EF%BC%8C%E4%B8%8D%E8%BF%87%E8%BF%91%E6%9C%9F%E7%9A%84%E4%B8%80%E4%BB%BD%E6%8A%A5%E5%91%8A%E6%98%BE%E7%A4%BA%EF%BC%8C%E4%B8%89%E6%98%9F%E5%B7%B2%E7%BB%8F%E4%BF%AE%E6%AD%A3%E4%BA%86%E5%87%BA%E7%8E%B0%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E5%B9%B6%E8%A1%A8%E7%A4%BA%E8%BF%99%E6%AC%BE%E5%8F%AF%E6%8A%98%E5%8F%A0%E6%89%8B%E6%9C%BA%E5%8D%B3%E5%B0%86%E5%9C%A86%E6%9C%88%E4%BB%BD%E9%87%8D%E6%96%B0%E4%B8%8A%E5%B8%82%E3%80%82<br>%E8%BF%99%E4%BB%BD%E6%8A%A5%E5%91%8A%E4%B8%AD%E6%8F%90%E5%88%B0%EF%BC%8C%E6%94%B9%E8%BF%9B%E5%90%8E%E7%9A%84%E4%BA%A7%E5%93%81%E7%9B%AE%E5%89%8D%E6%AD%A3%E5%9C%A8%E9%9F%A9%E5%9B%BD%E7%9A%84%E8%BF%90%E8%90%A5%E5%95%86%E9%82%A3%E9%87%8C%E8%BF%9B%E8%A1%8C%E6%B5%8B%E8%AF%95%EF%BC%8C%E9%A2%84%E8%AE%A1%E4%B8%89%E6%98%9F%E5%BE%88%E5%BF%AB%E5%B0%B1%E4%BC%9A%E5%AE%A3%E5%B8%83%E6%96%B0%E7%9A%84%E5%8F%91%E5%B8%83%E6%97%A5%E6%9C%9F%E3%80%82%E6%94%B9%E8%BF%9B%E7%9A%84Galaxy Fold%E9%A2%84%E8%AE%A1%E5%B0%86%E4%BA%8E6%E6%9C%88%E4%B8%8A%E5%B8%82%E3%80%82<br>%E6%AD%A4%E5%89%8D%EF%BC%8C%E4%B8%89%E6%98%9F%E7%94%B5%E5%AD%90%E7%A7%BB%E5%8A%A8%E9%80%9A%E4%BF%A1%E9%83%A8%E9%97%A8%E6%80%BB%E8%A3%81%E9%AB%98%E4%B8%9C%E7%9C%9F%E5%9C%A8%E6%8E%A5%E5%8F%97%E9%87%87%E8%AE%BF%E6%97%B6%E8%A1%A8%E7%A4%BA%EF%BC%8CGalaxy Fold%E5%B0%86%E5%9C%A8%E6%95%B0%E5%A4%A9%E5%86%85%E5%85%AC%E5%B8%83%E9%87%8D%E6%96%B0%E4%B8%8A%E5%B8%82%E7%9A%84%E6%97%B6%E9%97%B4%E3%80%82%E9%AB%98%E4%B8%9C%E7%9C%9F%E8%A1%A8%E7%A4%BA%EF%BC%8C%E5%85%AC%E5%8F%B8%E5%B7%B2%E7%BB%8F%E5%AE%A1%E6%9F%A5%E4%BA%86Galaxy Fold%E7%BC%BA%E9%99%B7%E9%97%AE%E9%A2%98%EF%BC%8C%E5%B9%B6%E5%B0%86%E5%9C%A8%E6%95%B0%E5%A4%A9%E5%86%85%E5%85%AC%E5%B8%83%E5%85%B7%E4%BD%93%E5%8E%9F%E5%9B%A0%EF%BC%8C%E5%B9%B6%E9%87%8D%E6%96%B0%E7%A1%AE%E5%AE%9A%E5%8C%97%E7%BE%8E%E5%9C%B0%E5%8C%BA%E7%9A%84%E4%B8%8A%E5%B8%82%E6%97%B6%E9%97%B4%E3%80%82<br>%E5%9C%A8%E8%A2%AB%E8%AE%B0%E8%80%85%E9%97%AE%E5%8F%8AGalaxy Fold%E8%83%BD%E5%90%A6%E5%9C%A8%E6%9C%AC%E6%9C%88%E9%87%8D%E6%96%B0%E4%B8%8A%E5%B8%82%E6%97%B6%EF%BC%8C%E9%AB%98%E4%B8%9C%E7%9C%9F%E7%A7%B0%E2%80%9C%E4%B8%8D%E4%BC%9A%E5%A4%AA%E6%99%9A%E2%80%9D%E3%80%82<br>%E6%8D%AE%E6%8A%A5%E9%81%93%EF%BC%8C%E4%B8%89%E6%98%9F%E5%B7%A5%E7%A8%8B%E5%9B%A2%E9%98%9F%E8%AE%A4%E4%B8%BA%EF%BC%8CGalaxy Fold%E7%9A%84%E5%B1%8F%E5%B9%95%E9%97%AE%E9%A2%98%E6%98%AF%E5%9B%A0%E4%B8%BA%E5%86%85%E5%B1%8F%E4%BF%9D%E6%8A%A4%E5%B1%82%E5%92%8C%E9%9D%A2%E6%9D%BF%E4%B9%8B%E9%97%B4%E7%9A%84%E7%BC%9D%E9%9A%99%EF%BC%8C%E4%BB%A5%E5%8F%8A%E6%8A%98%E5%8F%A0%E9%93%B0%E9%93%BE%E4%B8%AD%E5%A4%AE%E4%BD%8D%E7%BD%AE%E7%BC%BA%E5%8F%A3%EF%BC%8C%E9%80%A0%E6%88%90%E7%81%B0%E5%B0%98%E3%80%81%E6%9D%82%E8%B4%A8%E7%AD%89%E5%85%A5%E4%BE%B5OLED%E9%9D%A2%E6%9D%BF%E5%AF%BC%E8%87%B4%E7%9A%84%E3%80%82%E9%87%8D%E6%96%B0%E4%B8%8A%E5%B8%82%E7%9A%84Galaxy Fold%E5%B0%86%E5%87%8F%E5%B0%91%E5%86%85%E5%B1%8F%E4%BF%9D%E6%8A%A4%E5%B1%82%E5%92%8C%E9%9D%A2%E6%9D%BF%E4%B9%8B%E9%97%B4%E7%9A%84%E7%BC%9D%E9%9A%99%EF%BC%8C%E5%8A%A0%E5%9B%BA%E6%8A%98%E5%8F%A0%E9%93%B0%E9%93%BE%E4%B8%AD%E5%A4%AE%E4%BD%8D%E7%BD%AE%E7%BC%BA%E5%8F%A3%E7%AD%89%EF%BC%8C%E7%A1%AE%E4%BF%9D%E4%BF%AE%E5%A4%8D%E4%B9%8B%E5%89
2019-05-16 20:49:29.192 27160-27160/com.ihewro.focus D/PostDetailActivity:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.ihewro.focus.activity.PostDetailActivity$4.onSingleTapConfirmed(PostDetailActivity.java:242)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ 单击
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by li-xiaojun** [comment]
@ihewro 
问题已修复，更新到最新版试试。

**Comment by ihewro** [comment]
已经可以了，辛苦了！

**Comment by ihewro** [comment]
请问如果srcview为空，显示弹窗能否动画优化一点呢

现在是很突兀，我觉得可以改成从屏幕中间慢慢显示出来，就和显示对话框的动画一样。

当然只是一个建议
