### ISSUE TITLE
EmptyStackException

### ISSUE THREAD

**Issue by HardToWork** [li-xiaojun/XPopup#168]
我也不知道我怎么点的 就点出来错误了：BasePopupView.java:465
java.util.EmptyStackException
        at java.util.Stack.peek(Stack.java:102)
        at java.util.Stack.pop(Stack.java:84)
        at com.lxj.xpopup.core.BasePopupView$7.run(BasePopupView.java:465)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)

**Comment by li-xiaojun** [comment]
@HardToWork 最新版本已经修复了 ，请更新试试。
