### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by zqlq4ever** [li-xiaojun/XPopup#251]
`    java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$MarginLayoutParams.leftMargin' on a null object reference
        at com.lxj.xpopup.core.BasePopupView$1.run(BasePopupView.java:97)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)`

Le x620 android 6.0出现的

**Comment by li-xiaojun** [comment]
是最新版本吗？

**Comment by zqlq4ever** [comment]
> 是最新版本吗？
![image](https://user-images.githubusercontent.com/37474811/62746785-ec553500-ba83-11e9-8f1a-8a002b77e486.png)

`    private void initFreedomBeaconPop() {
        FreedomBeaconView freedomBeaconView = new FreedomBeaconView(this);
        mFreedomBeaconPop = new XPopup.Builder(mContext)
                .asCustom(freedomBeaconView);
        mFreedomBeaconPop.init();
    }`

对，activity初始化时，初始化了一些pop，沒有show,打开页面就崩了.

**Comment by li-xiaojun** [comment]
为什么要调用 mFreedomBeaconPop.init()；
你是从哪里看的这样用的，我demo和文档都没有这样写过。
弹窗的init方法是内部使用的，外面不要调用。

**Comment by zqlq4ever** [comment]
> 为什么要调用 mFreedomBeaconPop.init()；
> 你是从哪里看的这样用的，我demo和文档都没有这样写过。
> 弹窗的init方法是内部使用的，外面不要调用。
嗯，知道了，感谢大佬
