### ISSUE TITLE
图片预览点击保存会报NullPointerException

### ISSUE THREAD

**Issue by lovedren** [li-xiaojun/XPopup#312]
连续点击图片预览的保存，会报NullPointerException，错误日志如下：
Process: com.lxj.xpopupdemo, PID: 5876
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.widget.Toast.<init>(Toast.java:114)
        at android.widget.Toast.makeText(Toast.java:277)
        at android.widget.Toast.makeText(Toast.java:267)
        at com.lxj.xpopup.util.XPopupUtils$2$2$1.run(XPopupUtils.java:389)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6662)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by li-xiaojun** [comment]
最新版问题以及修复
