### ISSUE TITLE
使用PartShadowPopupView 的问题

### ISSUE THREAD

**Issue by me-xg** [li-xiaojun/XPopup#328]
在android 4.4 的机子上出现崩溃，跑demo没有问题，但是我从demo复制代码过去点击弹窗的时候就崩溃。
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x1
        at android.content.res.Resources.getResourceEntryName(Resources.java:1835)
        at com.lxj.xpopup.util.XPopupUtils.isNavBarVisible(XPopupUtils.java:323)
        at com.lxj.xpopup.impl.PartShadowPopupView.doAttach(PartShadowPopupView.java:98)
        at com.lxj.xpopup.core.AttachPopupView$1.run(AttachPopupView.java:84)
        at com.lxj.xpopup.util.XPopupUtils$1.run(XPopupUtils.java:139)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Steam-Ace** [comment]
检查发现后是因为状态栏的原因
at android.content.res.Resources.getResourceEntryName(Resources.java:1835)
at com.lxj.xpopup.util.XPopupUtils.isNavBarVisible(XPopupUtils.java:323)
好像是在判断 isNavBarVisible  的时候，引发的问题。我那个界面是透明状态栏，然后将图片伸到状态栏

**Comment by Jack-SunQi** [comment]
顶一下，也遇到同样的问题
