### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.lxj.xpopup.core.PopupInfo.isDismissOnBackPressed' on a null object reference

### ISSUE THREAD

**Issue by parcool** [li-xiaojun/XPopup#36]
先看复现步骤视频：
https://github.com/parcool/resources/blob/master/device-2019-02-02-095005.mp4
错误信息：
`
java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.lxj.xpopup.core.PopupInfo.isDismissOnBackPressed' on a null object reference
 at com.lxj.xpopup.core.BasePopupView$1.onKey(BasePopupView.java:78)
 at android.view.View.dispatchKeyEvent(View.java:12465)
 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1891)
 at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
 at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:449)
 at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
 at android.app.Activity.dispatchKeyEvent(Activity.java:3425)
 at android.support.v4.app.SupportActivity.superDispatchKeyEvent(ComponentActivity.java:108)
 at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
 at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
 at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
 at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
 at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
 at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:352)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5191)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5059)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4737)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4794)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4770)
 at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4933)
 at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2580)
 at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2090)
 at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2081)
 at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2557)
 at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:326)
 at android.os.Looper.loop(Looper.java:165)
 at android.app.ActivityThread.main(ActivityThread.java:6806)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
`

**Comment by li-xiaojun** [comment]
好的，我在回家的路上呢，等回家后我修复下。感谢你的issue，祝新年快乐发自我的华为手机-------- 原始邮件 --------主题：Re: [li-xiaojun/XPopup] java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.lxj.xpopup.core.PopupInfo.isDismissOnBackPressed' on a null object reference (#36)发件人：parcool 收件人：li-xiaojun/XPopup 抄送：Subscribed 这个问题很早之前就出现了，现在提的这issue是使用的最新版本1.3.3。
很大几率出现，如视频所示：
返回后页面无法点击了，所有view都在popupView下面，手指拖动响应的是popupView，点击返回按钮崩溃。
过年了，还来提个issue。。。

**Comment by li-xiaojun** [comment]
@parcool 
感谢你的issue，我抽空修复下。

**Comment by li-xiaojun** [comment]
@parcool 
您好，你反应的问题在最新版本`1.3.4`已经修复，更新下看看。
