### ISSUE TITLE
经常报错NullPointerException

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#363]
`
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at com.lxj.xpopup.util.KeyboardUtils.removeLayoutChangeListener(KeyboardUtils.java:78)
	at com.lxj.xpopup.core.BasePopupView.onDetachedFromWindow(BasePopupView.java:558)
	at android.view.View.dispatchDetachedFromWindow(View.java:17446)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3682)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3674)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3490)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6344)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:6321)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:123)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4599)
	at android.app.ActivityThread.-wrap5(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1702)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
`

**Comment by creativityingenuity** [comment]
同问

**Comment by jiuye2019** [comment]
自定义写的太菜了，什么都要传，一直报nullpointer

**Comment by creativityingenuity** [comment]
hahahaha

**Comment by li-xiaojun** [comment]
最新版已经修复这个问题
