### ISSUE TITLE
最新版 报错

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#404]
android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.lxj.xpopup.core.CenterPopupView.initPopupContent(SourceFile:2)
	at com.lxj.xpopup.impl.ConfirmPopupView.initPopupContent(SourceFile:1)
	at com.lxj.xpopup.core.BasePopupView.init(SourceFile:6)
	at com.lxj.xpopup.core.BasePopupView$3.run(SourceFile:4)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:7025)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by lodgkk** [comment]
是不是你的xml文件有问题了

**Comment by li-xiaojun** [comment]
@DuShuYuan 检测下你的布局

**Comment by DuShuYuan** [comment]
布局没有问题，原因是设置延迟弹出弹窗，然后切换到了后台，弹出时崩溃
