### ISSUE TITLE
1.8.11版本报错，Android系统 7.1.2 8.0，都报错。

### ISSUE THREAD

**Issue by LouisKooAndroid** [li-xiaojun/XPopup#406]
android.view.InflateException: Binary XML file line #25: Binary XML file line #25: Error inflating class androidx.appcompat.widget.AppCompatEditText
    Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class androidx.appcompat.widget.AppCompatEditText
    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.AppCompatEditText" on path: DexPathList[[zip file "/data/app/com.xtc.jl_scan-idJnV9f9Dl6TvIFR_UE90A==/base.apk"],nativeLibraryDirectories=[/data/app/com.xtc.jl_scan-idJnV9f9Dl6TvIFR_UE90A==/lib/arm64, /system/lib64, /system/vendor/lib64, /system/vendor/lib64/hw]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.lxj.xpopup.core.CenterPopupView.initPopupContent(CenterPopupView.java:39)
        at com.lxj.xpopup.impl.ConfirmPopupView.initPopupContent(ConfirmPopupView.java:47)
        **at com.lxj.xpopup.core.BasePopupView.init(BasePopupView.java:83)**
        at com.lxj.xpopup.core.BasePopupView$3.run(BasePopupView.java:209)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

以上是报错内容，我切换回1.8.10，使用正常。

**Comment by li-xiaojun** [comment]
试试1.9.3，应该修复了这个问题
