### ISSUE TITLE
这个库不支持组件化吗，不同组建饮用这个库，然后报错android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by lichengcheng098** [li-xiaojun/XPopup#407]
android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:94)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2181)
        at android.content.res.Resources.getLayout(Resources.java:1169)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
        at com.lxj.xpopup.core.BottomPopupView.initPopupContent(BottomPopupView.java:34)
        at com.lxj.xpopup.core.BasePopupView.init(BasePopupView.java:83)
        at com.lxj.xpopup.core.BasePopupView$3.run(BasePopupView.java:209)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by li-xiaojun** [comment]
一个UI库而已，和组件化没有什么关系。如果报错，请检查组件化的配置问题

**Comment by 50kg** [comment]
楼主怎么解决了，我这边组件化也出现了这个问题
