### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by wenge1215** [li-xiaojun/XPopup#42]
版本号：1.3.7

使用代码：
    private void showShopCardDialog() {
        if (mShopCardPopupView == null) {
            mShopCardPopupView = new ShopCardPopupView(this, mShopGoodsData);
            mShopCardPopupView.setChangeLisenter(this);
        } else {
            mShopCardPopupView.refreshData();
        }
        XPopup.get(this)
                .asCustom(mShopCardPopupView)
                .dismissOnTouchOutside(true)
                .atView(mViewLine)
                .show();
    }
操作场景：响应点击事件，当按钮被点击时展示，点击空白处时消失

错误信息：
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.mmtc.beautytreasure, PID: 11746
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
                                                                             at com.lxj.xpopup.XPopup$2$2.run(XPopup.java:148)
                                                                             at com.lxj.xpopup.core.BasePopupView$4.run(BasePopupView.java:301)
                                                                             at android.os.Handler.handleCallback(Handler.java:808)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                             at android.os.Looper.loop(Looper.java:166)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7529)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by li-xiaojun** [comment]
@wenge1215 
可以加我QQ 16167479 把代码发我一份，我帮你看看，因为我试了下没有复现。

**Comment by li-xiaojun** [comment]
@wenge1215 
在最新版本`1.3.9`已经修复，请更新看看。

**Comment by wenge1215** [comment]
已解决，感谢大佬！
