### ISSUE TITLE
第一次弹出是好的，第二次就出现资源未找到

### ISSUE THREAD

**Issue by gsn516** [li-xiaojun/XPopup#422]
三星s8（7.0）上是好的，华为（10.0）上有这个问题
自定义View继承BottomPopupView
报错内容如下：
/Resource: printErrorResource, maybe not a error because module has entative access to resource called by =android.content.res.HwResourcesImpl.printErrorResource:2634 android.content.res.ResourcesImpl.getResourceEntryName:377 android.content.res.Resources.getResourceEntryName:2229 com.lxj.xpopup.util.XPopupUtils.isNavBarVisible:323 com.lxj.xpopup.core.BasePopupView.applySize:169 com.lxj.xpopup.core.BasePopupView$1.run:106 

2020-04-17 15:54:56.664 2071-2071/com.nj.doc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nj.doc, PID: 2071
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7fffffff
        at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:380)
        at android.content.res.Resources.getResourceEntryName(Resources.java:2229)
        at com.lxj.xpopup.util.XPopupUtils.isNavBarVisible(XPopupUtils.java:323)
        at com.lxj.xpopup.core.BasePopupView.applySize(BasePopupView.java:169)
        at com.lxj.xpopup.core.BasePopupView$1.run(BasePopupView.java:106)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by li-xiaojun** [comment]
上代码
