### ISSUE TITLE
2.0.1 版本的【大图浏览弹窗】如果未传srcView，会导致崩溃

### ISSUE THREAD

**Issue by Carecluse** [li-xiaojun/XPopup#459]
photoView.setOnMatrixChangeListener(new OnMatrixChangedListener() {
                @Override
                public void onMatrixChanged(RectF rect) {
                Matrix matrix = new Matrix();
                    photoView.getSuppMatrix(matrix);
                    snapshotView.setSuppMatrix(matrix); **// snapshotView 为 null**
                }
            });

崩溃信息如下：
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.lxj.xpopup.photoview.PhotoView.setSuppMatrix(android.graphics.Matrix)' on a null object reference
        at com.lxj.xpopup.core.ImageViewerPopupView$PhotoViewAdapter$1.onMatrixChanged(ImageViewerPopupView.java:483)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.setImageViewMatrix(PhotoViewAttacher.java:584)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.checkAndDisplayMatrix(PhotoViewAttacher.java:594)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.setRotationBy(PhotoViewAttacher.java:309)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.resetMatrix(PhotoViewAttacher.java:573)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.updateBaseMatrix(PhotoViewAttacher.java:679)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.update(PhotoViewAttacher.java:519)
        at com.lxj.xpopup.photoview.PhotoView.setImageDrawable(PhotoView.java:107)

**Comment by li-xiaojun** [comment]
2.0.2版本已修复
