### ISSUE TITLE
Crash when close fragment containing a BottomListPopupView

### ISSUE THREAD

**Issue by anhtuanmai** [li-xiaojun/XPopup#483]
version: **com.lxj:xpopup:2.0.6**
phone: Xiaomi Note 5

```
E/AndroidRuntime: FATAL EXCEPTION: main
    PID: 29559
    java.lang.RuntimeException: Unable to destroy activity {MainActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4447)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4465)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123)
        at androidx.lifecycle.ReportFragment.onDestroy(ReportFragment.java:108)
        at android.app.Fragment.performDestroy(Fragment.java:2768)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1432)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1562)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1623)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
        at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3012)
        at android.app.FragmentController.dispatchDestroy(FragmentController.java:244)
        at android.app.Activity.performDestroy(Activity.java:7292)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1250)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4465) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6635) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 
     Caused by: java.lang.NullPointerException: Attempt to write to field 'android.view.View com.lxj.xpopup.core.PopupInfo.atView' on a null object reference
        at com.lxj.xpopup.core.BasePopupView.destroy(BasePopupView.java:651)
        at com.lxj.xpopup.core.BasePopupView.onDestroy(BasePopupView.java:645)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123) 
        at androidx.lifecycle.ReportFragment.onDestroy(ReportFragment.java:108) 
        at android.app.Fragment.performDestroy(Fragment.java:2768) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1432) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1562) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1623) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032) 
        at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3012) 
        at android.app.FragmentController.dispatchDestroy(FragmentController.java:244) 
        at android.app.Activity.performDestroy(Activity.java:7292) 
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1250) 
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4434) 
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4465) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6635) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823) 

```

**Comment by anhtuanmai** [comment]
I resolved the problem by set
`isDestroyOnDismiss = false`

**Comment by li-xiaojun** [comment]
> 或者更新到2.0.6-rc3 也能解决



> I resolved the problem by set
> `isDestroyOnDismiss = false`
> 
> 或者更新到2.0.6-rc3 也能解决
