### ISSUE TITLE
大图浏览保存图片闪退

### ISSUE THREAD

**Issue by lodgkk** [li-xiaojun/XPopup#485]
点击图片,弹大图浏览dialog,然后点保存,闪退,报错信息如下:
MtaSDK.CaughtExp: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.lxj.xpopup.core.ImageViewerPopupView$5.onGranted(ImageViewerPopupView.java:448)
        at com.lxj.xpopup.util.XPermission.requestCallback(XPermission.java:332)
        at com.lxj.xpopup.util.XPermission.request(XPermission.java:275)
        at com.lxj.xpopup.core.ImageViewerPopupView.save(ImageViewerPopupView.java:455)
        at com.lxj.xpopup.core.ImageViewerPopupView.onClick(ImageViewerPopupView.java:435)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7138)
        at android.view.View.access$3500(View.java:811)
        at android.view.View$PerformClick.run(View.java:27419)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by lodgkk** [comment]
需要设置这个参数才正常,isInfinite(true)

**Comment by li-xiaojun** [comment]
用的哪个版本？

**Comment by lodgkk** [comment]
最新的版本,2.0.0-rc3

**Comment by li-xiaojun** [comment]
我试了下没复现，你试试Demo能复现吗，如果Demo没有问题，可能你的代码有问题。可以贴下相关代码

**Comment by lodgkk** [comment]
private void goPhoto(ImageView imageView, String path) {
        List<Object> list = new ArrayList<>();
        list.add(path);
        new XPopup.Builder(imageView.getContext())
                .asImageViewer(imageView, 2, list, new OnSrcViewUpdateListener() {
                    @Override
                    public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                        // 作用是当Pager切换了图片，需要更新源View
//                            popupView.updateSrcView((AppCompatImageView) recyclerView.getChildAt(position));
                    }
                }, new XDialogImageLoader())
                .isInfinite(true)
                .show();
    }
上面的.isInfinite(true)加进去之后才正常

**Comment by li-xiaojun** [comment]
你的list只有1个，为啥指定2

**Comment by lodgkk** [comment]
这个不是数量,那个是currentPosition
