### ISSUE TITLE
isDestroyOnDismiss设置为true会崩溃

### ISSUE THREAD

**Issue by zengwenling** [li-xiaojun/XPopup#486]
Caused by: java.lang.NullPointerException: Attempt to write to field 'android.view.View com.lxj.xpopup.core.PopupInfo.atView' on a null object reference
        at com.lxj.xpopup.core.BasePopupView.destroy(BasePopupView.java:649)
        at com.lxj.xpopup.core.BasePopupView.onDestroy(BasePopupView.java:643)
        at java.lang.reflect.Method.invoke(Native Method)
![image](https://user-images.githubusercontent.com/6247675/86863546-fea97a00-c0fd-11ea-8ba4-8f4b8f18a25d.png)

**Comment by li-xiaojun** [comment]
用的什么版本

**Comment by li-xiaojun** [comment]
更新到最新版本
