### ISSUE TITLE
2.1.4  IllegalStateException: Already in the pool!

### ISSUE THREAD

**Issue by DuShuYuan** [li-xiaojun/XPopup#578]
**XPopup版本**
2.1.4

**手机系统和型号**
9 (42)   8.1.0 (31)   8.0.0 (10)   7.1.2 (1)   7.1.1 (1)   7.0 (15)   6.0.1 (13)   6.0 (7)   5.1.1 (4)   5.0.1 (1)   4.4.4 (3)   4.4.2 (2)   10 (43)  

**描述你的问题**

不知道哪个弹窗，各系统版本都有报错
报错：
java.lang.IllegalStateException: Already in the pool!
	at android.util.Pools$SimplePool.release(Pools.java:112)
	at android.util.Pools$SynchronizedPool.release(Pools.java:161)
	at android.view.VelocityTracker.recycle(VelocityTracker.java:85)
	at com.lxj.xpopup.widget.SmartDragLayout.onTouchEvent(SmartDragLayout.java:23)
	at android.view.View.dispatchTouchEvent(View.java:8287)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2292)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at com.lxj.xpopup.widget.SmartDragLayout.dispatchTouchEvent(SmartDragLayout.java:5)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2294)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2294)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2294)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2064)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2294)
	at android.view.ViewGroup.cancelAndClearTouchTargets(ViewGroup.java:2157)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2710)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2997)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5650)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:5627)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:376)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:324)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
	at android.app.Dialog.dismissDialog(Dialog.java:368)
	at android.app.Dialog.dismiss(Dialog.java:351)
	at com.lxj.xpopup.core.BasePopupView$6.run(BasePopupView.java:18)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by li-xiaojun** [comment]
2.1.4之前有这个问题，2.1.4应该是没有的，确定是2.1.4报错的吗？我用华为mate20，红米8都无法复现

**Comment by DuShuYuan** [comment]
确认是2.1.4 以前用的2.0.11，更新后才出现这个问题

**Comment by li-xiaojun** [comment]
更新到2.1.7试试

**Comment by DuShuYuan** [comment]
> 更新到2.1.7试试

ok  新版上线后再看看效果
