### ISSUE TITLE
XPopup 2.1.4版本 图片预览时导致的崩溃 Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by vanzh** [li-xiaojun/XPopup#636]
**XPopup版本**
如2.1.4

**手机系统和型号**
华为Mate8 Android 8.0

**描述你的问题**
打开图片预览时，保存图片报如下错误：
ava.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
    at android.app.ActivityThread.-wrap12(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.Activity.onCreate(Activity.java:1081)
    at com.lxj.xpopup.util.XPermission$PermissionActivity.onCreate(Native Method)
    at android.app.Activity.performCreate(Activity.java:7383)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
    ... 9 more
Back traces ends.

从日志上看，是PermissionActivity 在请求存储权限时导致的。
我的项目中的Activity 指定使用  android:screenOrientation="portrait"

目前的暂时的处理方案是 在弹框之前先请求存储权限后，弹出图片预览，再保存就没有问题。

但是我认为，应该可以在PermissionActivity 里适配，从而避免崩溃。

**Comment by li-xiaojun** [comment]
这个我还不太确定是怎么产生的，我尝试复现，但是没有出现这个问题
