### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 330676687** [li-xiaojun/XPopup#672]
从2.2.13更新到2.2.14以上版本出现 umeng上捕捉的 自己无法复现

> Back traces starts.
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child&#39;s parent first.
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5958)
	at android.view.ViewGroup.addView(ViewGroup.java:5777)
	at android.view.ViewGroup.addView(ViewGroup.java:5749)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:572)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:553)
	at android.app.Dialog.setContentView(Dialog.java:863)
	at com.lxj.xpopup.core.FullScreenDialog.onCreate(FullScreenDialog.java:86)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:702)
	at android.app.Dialog.show(Dialog.java:424)
	at com.lxj.xpopup.core.BasePopupView.attachToHost(BasePopupView.java:155)
	at com.lxj.xpopup.core.BasePopupView.access$000(BasePopupView.java:44)
	at com.lxj.xpopup.core.BasePopupView$1.run(BasePopupView.java:113)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Back traces ends.

**Comment by li-xiaojun** [comment]
更新到最新版本即可
