### ISSUE TITLE
后台弹窗奔溃

### ISSUE THREAD

**Issue by Jasperben** [li-xiaojun/XPopup#705]
**XPopup版本**
2.2.23

2021-04-27 09:48:35.033 32673-32673/com.lxj.xpopupdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lxj.xpopupdemo, PID: 32673
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:447)
        at android.view.View.<init>(View.java:4815)
        at android.view.View.<init>(View.java:4957)
        at android.view.ViewGroup.<init>(ViewGroup.java:660)
        at android.view.ViewGroup.<init>(ViewGroup.java:656)
        at android.view.ViewGroup.<init>(ViewGroup.java:652)
        at android.view.ViewGroup.<init>(ViewGroup.java:648)
        at android.widget.FrameLayout.<init>(FrameLayout.java:78)
        at com.lxj.xpopup.core.BasePopupView.<init>(Unknown Source:0)
        at com.lxj.xpopup.core.CenterPopupView.<init>(Unknown Source:0)
        at com.lxj.xpopup.impl.ConfirmPopupView.<init>(Unknown Source:0)
        at b.c.c.e$b.a(Unknown Source:9)
        at b.c.c.e$b.a(Unknown Source:9)
        at com.lxj.xpopupdemo.fragment.f$d$a.run(Unknown Source:29)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by li-xiaojun** [comment]
更新到最新版试试
