### ISSUE TITLE
大图的弹窗，当图片未加载成功的时候点击保存，就会空指针

### ISSUE THREAD

**Issue by fansangg** [li-xiaojun/XPopup#71]
getImageFile里返回null，就会报以下错误

java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:140)
        at com.lxj.xpopup.util.XPopupUtils$2.run(XPopupUtils.java:325)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

**Comment by li-xiaojun** [comment]
@fansangg 
感谢建议，下班版本修复。

**Comment by li-xiaojun** [comment]
@fansangg
最新版本已经修复。
