### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'boolean com.lxj.xpopup.core.PopupInfo.isViewMode' on a null object reference

### ISSUE THREAD

**Issue by jiaoyongzhi** [li-xiaojun/XPopup#721]
**XPopup版本**
2.3.3

**手机系统和型号**
华为 p30 Android 10

**描述你的问题**
最好能上代码截图和问题截图
java.lang.NullPointerException: Attempt to read from field 'boolean com.lxj.xpopup.core.PopupInfo.isViewMode' on a null object reference
	at com.lxj.xpopup.core.BasePopupView.show(BasePopupView.java:109)
	at android.view.View.performClick(View.java:7281)
	at android.view.View.performClickInternal(View.java:7255)
	at android.view.View.access$3600(View.java:828)
	at android.view.View$PerformClick.run(View.java:27925)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by li-xiaojun** [comment]
更新到2.3.4即可
