### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'android.graphics.PointF 

### ISSUE THREAD

**Issue by ydslib** [li-xiaojun/XPopup#747]
**XPopup版本**
如2.4.0

**手机系统和型号**
华为VOG-AL00 Android 10

**描述你的问题**
`Process Name: 'com.codemao.grow'
Thread Name: 'main'
Back traces starts.
java.lang.NullPointerException: Attempt to read from field 'android.graphics.PointF com.lxj.xpopup.core.PopupInfo.touchPoint' on a null object reference
	at com.lxj.xpopup.core.AttachPopupView.doAttach(AttachPopupView.java:116)
	at com.lxj.xpopup.core.AttachPopupView$1.run(AttachPopupView.java:65)
	at com.lxj.xpopup.util.XPopupUtils$1$1.run(XPopupUtils.java:169)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
Back traces ends.`

**Comment by li-xiaojun** [comment]
代码发下

**Comment by li-xiaojun** [comment]
更新到2.4.4即可
