### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'java.lang.Boolean com.lxj.xpopup.core.PopupInfo.hasStatusBarShadow' on a null object reference

### ISSUE THREAD

**Issue by jiaoyongzhi** [li-xiaojun/XPopup#752]
**XPopup版本**
2.2.23

**手机系统和型号**
华为ASK-AL00x  android9

**描述你的问题**
	at com.android.internal.policy.DecorView.draw(DecorView.java:909)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3715)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3378)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2716)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1640)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7929)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1099)
	at android.view.Choreographer.doCallbacks(Choreographer.java:900)
	at android.view.Choreographer.doFrame(Choreographer.java:816)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1085)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7586)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Back traces ends.

**Comment by li-xiaojun** [comment]
版本太旧，请更新到最新版本
