### ISSUE TITLE
无网环境下空指针

### ISSUE THREAD

**Issue by pokerfaceCmy** [li-xiaojun/XPopup#754]
**XPopup版本**
2.4.4

**手机系统和型号**
小米k20pro  Android 11

**描述你的问题**

```
2021-07-12 09:45:11.965 5944-5944/com.poker.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.poker.pixiu, PID: 5944
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lxj.xpopup.animator.ShadowBgAnimator.animateDismiss()' on a null object reference
        at com.lxj.xpopup.core.BasePopupView.doDismissAnimation(BasePopupView.java:475)
        at com.lxj.xpopup.core.BasePopupView.dismiss(BasePopupView.java:565)
        at com.poker.common.mvvm.ui.BaseActivity.dismissLoading(BaseActivity.kt:125)
        at com.poker.common.mvvm.IUIActionEventObserver$DefaultImpls.generateActionEvent$lambda-2(ActionEventObserver.kt:86)
        at com.poker.common.mvvm.IUIActionEventObserver$DefaultImpls.lambda$k0lBtq4rIDVz-CCam6QMYKsYROs(Unknown Source:0)
        at com.poker.common.mvvm.-$$Lambda$IUIActionEventObserver$DefaultImpls$k0lBtq4rIDVz-CCam6QMYKsYROs.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.poker.common.mvvm.IViewModelActionEvent$DefaultImpls.dismissLoading(ActionEventObserver.kt:112)
        at com.poker.common.mvvm.vm.BaseViewModel.dismissLoading(BaseViewModel.kt:19)
        at com.poker.common.mvvm.vm.BaseViewModel$enqueue$1.invokeSuspend(BaseViewModel.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by li-xiaojun** [comment]
更新到最新版本即可
