### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by jameskwan110** [li-xiaojun/XPopup#763]
**XPopup版本**
2.4.8

**手机系统和型号**
一加6

**描述你的问题**
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lxj.xpopup.animator.ShadowBgAnimator.animateDismiss()' on a null object reference
at com.lxj.xpopup.core.BasePopupView.doDismissAnimation(BasePopupView.java:474)
at com.lxj.xpopup.core.BasePopupView.dismiss(BasePopupView.java:564)

**Comment by jameskwan110** [comment]
升级版本即可
