### ISSUE TITLE
图片浏览闪退

### ISSUE THREAD

**Issue by Iduace** [li-xiaojun/XPopup#775]
**XPopup版本**
2.5.3之后版本

**手机系统和型号**
nova 5i

**描述你的问题**

new XPopup.Builder(getContext())
                        .asImageViewer(null, url, new SmartGlideImageLoader())
                        .show();

AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 14405
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.lxj.xpopup.photoview.PhotoView.getDrawable()' on a null object reference
        at com.lxj.xpopup.util.SmartGlideImageLoader.loadImage(SmartGlideImageLoader.java:54)
        at com.lxj.xpopup.core.ImageViewerPopupView$PhotoViewAdapter.instantiateItem(ImageViewerPopupView.java:493)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1562)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6903)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:896)
        at android.view.View.measure(View.java:24742)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3208)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1971)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2292)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1854)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8086)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:776)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by li-xiaojun** [comment]
@Iduace 更新到最新版本试试

**Comment by Iduace** [comment]
2.53开始到最新版本里.asImageViewer()的第一个参数null的话就会闪退
