### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by oudengding** [li-xiaojun/XPopup#778]
**XPopup版本**
2.4.3

**手机系统和型号**
荣耀10X

**描述你的问题**
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lxj.xpopup.animator.ShadowBgAnimator.animateDismiss()' on a null object reference
        at com.lxj.xpopup.core.BasePopupView.doDismissAnimation(BasePopupView.java:473)
        at com.lxj.xpopup.core.BasePopupView.dismiss(BasePopupView.java:563)

**Comment by li-xiaojun** [comment]
@oudengding 更新到最新版本即可
