### ISSUE TITLE
2.5.6查看大图闪退，改到2.5.8无法引用

### ISSUE THREAD

**Issue by yecaler** [li-xiaojun/XPopup#788]
**XPopup版本**
如2.5.8

**手机系统和型号**
MI 8 Android 10

**描述你的问题**
Execution failed for task ':app:javaPreCompileDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find XPopup-2.5.8.jar (com.github.li-xiaojun:XPopup:2.5.8).
     Searched in the following locations:
         https://mirrors.tencent.com/nexus/repository/maven-public/com/github/li-xiaojun/XPopup/2.5.8/XPopup-2.5.8.jar

**2.5.6出现查看图片功能出现问题，**
问题如下：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.lxj.xpopup.photoview.PhotoView.getDrawable()' on a null object reference
**从2.5.6改到2.5.8后，报错，无法引用。**

![图片](https://user-images.githubusercontent.com/25024969/129342772-42d7962c-1c69-476e-994b-f60fff976ced.png)

**Comment by yecaler** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.lxj.xpopup.photoview.PhotoView.getDrawable()' on a null object reference
        at com.lxj.xpopup.util.SmartGlideImageLoader.loadImage(SmartGlideImageLoader.java:54)
        at com.lxj.xpopup.core.ImageViewerPopupView$PhotoViewAdapter.instantiateItem(ImageViewerPopupView.java:482)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6845)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6845)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:909)
        at android.view.View.measure(View.java:22451)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2612)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1621)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1894)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1503)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7197)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:935)
        at android.view.Choreographer.doCallbacks(Choreographer.java:747)
        at android.view.Choreographer.doFrame(Choreographer.java:677)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:921)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6893)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

**Comment by li-xiaojun** [comment]
@yecaler 引用问题解决了吗

**Comment by yecaler** [comment]
引用的问题解决了。但是会出现这个问题。
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.lxj.xpopup.photoview.PhotoView.getDrawable()' on a null object reference
        at com.lxj.xpopup.util.SmartGlideImageLoader.loadImage(SmartGlideImageLoader.java:54)
        at com.lxj.xpopup.core.ImageViewerPopupView$PhotoViewAdapter.instantiateItem(ImageViewerPopupView.java:482)
        at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:775)
        at android.view.View.measure(View.java:24856)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3119)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1931)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
        at android.view.Choreographer.doCallbacks(Choreographer.java:865)
        at android.view.Choreographer.doFrame(Choreographer.java:800)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by li-xiaojun** [comment]
更新到2.5.9即可

**Comment by yecaler** [comment]
刚才试了一下，还是会出现。这是我的代码：
recyclerviewImg.setLayoutManager(new GridLayoutManager(mContext, 3));
                    recyclerviewImg.setNestedScrollingEnabled(false);
                    recyclerviewImg.setFocusableInTouchMode(false);
                    recyclerviewImg.requestFocus();
                    PictureAdapter pictureAdapter = new PictureAdapter();
                    recyclerviewImg.setAdapter(pictureAdapter);
                    pictureAdapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
                        @Override
                        public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                            new XPopup.Builder(mContext).asImageViewer((RoundedImageView) adapter.getViewByPosition(recyclerviewImg, position, R.id.show_image), position, stringList, new OnSrcViewUpdateListener() {
                                @Override
                                public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                                    // 作用是当Pager切换了图片，需要更新源View
                                    popupView.updateSrcView((RoundedImageView) adapter.getViewByPosition(recyclerviewImg, position, R.id.show_image));
                                }
                            }, new SmartGlideImageLoader())
                                    .show();
                        }
                    });
是一个跟朋友圈差不多的功能，recyclerview嵌套recyclerview。

**Comment by li-xiaojun** [comment]
@yecaler 是不是你ImageView没找对，你把你 找到的View打印下，看看是不是ImageView

**Comment by yecaler** [comment]
解决了，感谢大佬，问题的原因是imageview找的不正确，
问题：recyclerview嵌套recyclerview，点击大图，闪退，图片放大位置不对。
解决方案： 
new XPopup.Builder(mContext).asImageViewer((RoundedImageView) adapter.getViewByPosition(position, R.id.show_image), position, stringList, new OnSrcViewUpdateListener() {
                                @Override
                                public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                                    // 作用是当Pager切换了图片，需要更新源View
                                    popupView.updateSrcView((RoundedImageView) adapter.getViewByPosition(position, R.id.show_image));
                                }
                            }, new SmartGlideImageLoader())
                                    .show();
前面(RoundedImageView) adapter.getViewByPosition(position, R.id.show_image)参数写错了导致的。
以供参考。
