### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.lxj.xpopup.widget.PartShadowContainer.getChildCount()' on a null object reference

### ISSUE THREAD

**Issue by zhufeixiang** [li-xiaojun/XPopup#816]
**XPopup版本**
如2.5.15

**手机系统和型号**
一加6T Android 10

**描述你的问题**
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.lxj.xpopup.widget.PartShadowContainer.getChildCount()' on a null object reference
        at com.lxj.xpopup.impl.PartShadowPopupView.initPopupContent(PartShadowPopupView.java:43)
        at com.lxj.xpopup.core.BasePopupView.init(BasePopupView.java:186)
        at com.lxj.xpopup.core.BasePopupView$1.run(BasePopupView.java:132)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by zhufeixiang** [comment]
继承布局的方法写错了。。。。

**Comment by tyr285687545** [comment]
不明白哪里写错了....我也会这样
