### ISSUE TITLE
asImageViewer浏览图片功能，加载url为本地图片时，无法加载图片？

### ISSUE THREAD

**Issue by luomaa** [li-xiaojun/XPopup#821]
**XPopup版本**
如2.5.15

**手机系统和型号**
华为 平板Android 7 华为mate30 

**描述你的问题**
浏览图片功能，加载url为本地图片时，无法加载图片？
我把demo中的URL 换成了，本地图片地址路径如：     list.add("/storage/emulated/0/AiTerminalPhoto/1632297582781.jpg");
recycleView也无法正常加载？点击图片浏览大图也无法加载本地的图片成功。

在我自己的项目中，图片加载用glide-4.9.0，可以加载recycleView中本地图片可以成功显示（说明我的代码部分无问题）：
  Glide.with(context).load(bean.imgPath).into(mIvPhoto);//我的rv可以正常展示图片，其bean.imgPath = "/storage/emulated/0/AiTerminalPhoto/1632297582781.jpg";

但是点击图片浏览图片是，本地的图片加载失败：
        //2. 设置点击
        mIvPhoto.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                List<Object> list = Arrays.asList(adapter.listData.toArray());//listData 的实体bean中url为本地图片路径如“/storage/emulated/0/AiTerminalPhoto/1632297582781.jpg”

                new XPopup.Builder(context)
                        .asImageViewer(mIvPhoto, position, list,
                                false, true, -1, -1, -1, true,
                                Color.rgb(32, 36, 46),
                                new OnSrcViewUpdateListener() {
                                    @Override
                                    public void onSrcViewUpdate(ImageViewerPopupView popupView, int position) {
                                        RecyclerView rv = (RecyclerView) itemView.getParent();//和demo一致 只有imageview
                                        popupView.updateSrcView((ImageView) rv.getChildAt(position));
                                    }
                                }, new SmartGlideImageLoader( R.mipmap.ic_launcher), null)
                        .show();
            }
        });

以上代码，浏览大图显示错误图片R.mipmap.ic_launcher，无法显示正确的本地图片。

**Comment by li-xiaojun** [comment]
uri是交给glide加载，如果加载不出来，检测下路径是否正确

**Comment by luomaa** [comment]
> uri是交给glide加载，如果加载不出来，检测下路径是否正确

uri是正确的哦，因为我自己的展示也是本地图片glide加载的，并且加载本地相册图片正常显示，只是用了asImageViewer 不能正常显示即便是您的demo也不显示本地的uri图片，网络的url链接的图片是可以的，不知道是什么原因？

**Comment by luomaa** [comment]
> uri是交给glide加载，如果加载不出来，检测下路径是否正确

1.旧的问题未解决，新的问题，用单张图片浏览图片时可以正常显示，但是我在双指触摸缩放图片时崩溃了？因为我看了文档说加载大图已处理了？我加载的图片内存为2~3M，2592*1944，

   new XPopup.Builder(context)
                        .asImageViewer(mIvPhoto, “/storage/emulated/0/AiTerminalPhoto/1632297582781.jpg”, new SmartGlideImageLoader())
                        .show();

2.旧问题：那么多图浏览时，因为需要传的参数是list<Object>类型，请问这里传的list是否正确？List list = Arrays.asList(adapter.listData.toArray());//listData 为List<ImgBean>

单图模式浏览触摸，奔溃日志：
E/MessageQueue-JNI: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM
        at android.view.VelocityTracker.obtain(VelocityTracker.java:59)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:498)
        at com.lxj.xpopup.photoview.PhotoViewAttacher.onTouch(PhotoViewAttacher.java:410)
        at android.view.View.dispatchTouchEvent(View.java:10019)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.lxj.xpopup.widget.PhotoViewContainer.dispatchTouchEvent(PhotoViewContainer.java:87)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:545)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1811)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:806)
        at com.lxj.xpopup.core.FullScreenDialog.dispatchTouchEvent(FullScreenDialog.java:191)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:507)
        at android.view.View.dispatchPointerEvent(View.java:10243)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by li-xiaojun** [comment]
如果是大图，SmartGlideImageLoader(true)，看文档说明，或者SmartGlideImageLoader的构造函数

**Comment by luomaa** [comment]
> 如果是大图，SmartGlideImageLoader(true)，看文档说明，或者SmartGlideImageLoader的构造函数

确定使用了SmartGlideImageLoader(true,R.mipmap.ic_launcher)，他可以加载大图成功，但是是多个手指触摸和缩放的时候，就会百分百oom，您可以复现，我的图片为2048x1536，2M左右图片：

**Comment by li-xiaojun** [comment]
@luomaa 我这边用10M的图片测试都没问问题
