### ISSUE TITLE
升级2.6.2后报错

### ISSUE THREAD

**Issue by guozhiqiang123** [li-xiaojun/XPopup#839]
**XPopup版本**
如2.6.2

**手机系统和型号**
小米6

**描述你的问题**
 java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoSuchFieldError: No static field abc_text_select_handle_left_mtrl_dark of type I in class Landroidx/appcompat/R$drawable; or its superclasses (declaration of 'androidx.appcompat.R$drawable' appears in base.apk!classes2.dex)

**Comment by li-xiaojun** [comment]
@guozhiqiang123  两个问题，1：你项目是不是androidx的？2：你的complieSdkVersion是多少？
