### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by XuXiaoMing123** [li-xiaojun/XPopup#863]
xpopup版本：2.5.18
android系统：7.1.2  
机型：DT1901A，NX627J，WLZ-AN00等

k_ac:system
k_ct:exception
Exception message:
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.getGlobalVisibleRect(android.graphics.Rect)' on a null object reference
	at com.lxj.xpopup.core.BasePopupView.onTouchEvent()
	at android.view.View.dispatchTouchEvent(View.java:10023)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2653)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2334)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2291)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2291)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2659)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2291)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:806)
	at e.q.b.h.a.dispatchTouchEvent()
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
	at android.view.View.dispatchPointerEvent(View.java:10243)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:6161)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
Back traces ends.

**Comment by li-xiaojun** [comment]
@XuXiaoMing123 用最新版本

**Comment by XuXiaoMing123** [comment]
好的
