### ISSUE TITLE
使用Hilt 获取context的时候出问题

### ISSUE THREAD

**Issue by XuJhin** [li-xiaojun/XPopup#872]
**XPopup版本**
如2.6.8

**手机系统和型号**
pixel3.  android 12

**描述你的问题**
使用hilt时出错，之前使用2.5.17没问题
   java.lang.ClassCastException: dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper cannot be cast to android.app.Activity
        at com.lxj.xpopup.core.BasePopupView.getActivityContentView(BasePopupView.java:192)
        at com.lxj.xpopup.core.BasePopupView.show(BasePopupView.java:100)

**Comment by li-xiaojun** [comment]
@XuJhin XPopup要求context必须是Activity类型
