### ISSUE TITLE
报错了，drawable/text_cursor_material has unresolved theme attributes!

### ISSUE THREAD

**Issue by ChenJia-X** [li-xiaojun/XPopup#95]
Resources: Drawable android:drawable/text_cursor_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getDrawable(Resources.java:746)
        at com.lxj.xpopup.util.XPopupUtils.setCursorDrawableColor(XPopupUtils.java:147)
        at com.lxj.xpopup.impl.InputConfirmPopupView.applyPrimaryColor(InputConfirmPopupView.java:46)
        at com.lxj.xpopup.impl.ConfirmPopupView.initPopupContent(ConfirmPopupView.java:39)
        at com.lxj.xpopup.impl.InputConfirmPopupView.initPopupContent(InputConfirmPopupView.java:38)
        at com.lxj.xpopup.core.BasePopupView.init(BasePopupView.java:129)
        at com.lxj.xpopup.XPopup$2.run(XPopup.java:136)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6334)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by li-xiaojun** [comment]
附上你的机型和系统版本。

**Comment by ChenJia-X** [comment]
一加5 Android7.1

> 附上你的机型和系统版本。

**Comment by li-xiaojun** [comment]
@ChenJia-X
是运行报错还是编译报错。

**Comment by ChenJia-X** [comment]
> @ChenJia-X
> 是运行报错还是编译报错。

运行时报错，但是不会crash

**Comment by li-xiaojun** [comment]
@ChenJia-X 
最新版本1.6.7已修复此问题。
