### ISSUE TITLE
2.8.11版本闪退bug

### ISSUE THREAD

**Issue by jiqianwen** [li-xiaojun/XPopup#996]
**XPopup版本**
如2.8.11

**手机系统和型号**
所有机型

**描述你的问题**
************* Crash Head ****************
Time Of Crash      : 2022_07_11-13_47_06
Rom Info           : RomInfo{name=huawei, version=12.0.0}
Device Manufacturer: HUAWEI
Device Model       : ANG-AN00
Android Version    : 10
Android SDK        : 29
App VersionName    : 7.5.3
App VersionCode    : 753
************* Crash Head ****************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacksAndMessages(java.lang.Object)' on a null object reference
	at com.lxj.xpopup.core.BasePopupView.onDetachedFromWindow(BasePopupView.java:819)
	at com.lxj.xpopup.core.CenterPopupView.onDetachedFromWindow(CenterPopupView.java:78)
	at android.view.View.dispatchDetachedFromWindow(View.java:20166)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4047)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4033)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4033)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:4033)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4879)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8254)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:8219)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:598)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:529)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:200)
	at android.app.Dialog.dismissDialog(Dialog.java:841)
	at android.app.Dialog.dismiss(Dialog.java:821)
	at com.lxj.xpopup.core.BasePopupView.destroy(BasePopupView.java:798)
	at com.lxj.xpopup.core.BasePopupView.onDetachedFromWindow(BasePopupView.java:826)
	at com.lxj.xpopup.core.CenterPopupView.onDetachedFromWindow(CenterPopupView.java:78)
	at com.lxj.xpopup.core.BasePopupView.onDestroy(BasePopupView.java:769)
	at com.iccapp.module.common.widget.dialog.MessageXPopup.onDestroy(MessageXPopup.java:100)
	at java.lang.reflect.Method.invoke(Native Method)
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:222)
 Caused by: java.lang.RuntimeException: Failed to call observer method
	at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:232)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:199)
	at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:190)
	at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:40)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
	at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPreDestroyed(ReportFragment.java:224)
	at android.app.Activity.dispatchActivityPreDestroyed(Activity.java:1443)
	at android.app.Activity.performDestroy(Activity.java:8473)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1355)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5863)
 Caused by: java.lang.RuntimeException: Unable to destroy activity {com.hfl.action/com.iccapp.module.common.mine.activity.SetUpActivity}: java.lang.RuntimeException: Failed to call observer method
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5878)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5908)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by li-xiaojun** [comment]
2.8.12已修复
